apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fleet-persistence
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: standard-rwo
